title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Live like you mean it.
permalink: ':title/'
baseurl: "/
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #https://twitter.com/soffline1

# Author Settings
author: Agustin Amici # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am the creator of the soffline method # add description
social-twitter: @soffline1  
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: soffline7@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
